version: '3.7'
services:
  talpa:
    restart: "no"
    build:
      context: ./talpa
      dockerfile: ./Dockerfile
    env_file:
      - ./.env
    depends_on:
      - "mongo"
    volumes:
      - ./talpa:/usr/src/app
  mongo:
    image: mongo
    restart: always
    env_file:
      - './.env'
    ports:
      - 27017:27017
    volumes:
      - ~/talpa_mongo_data:/data/db